/*
 * eeprom_config.h
 *
 *  Created on: Oct 11, 2016
 *      Author: felix
 */

#ifndef PRODUCT_WATERHEATER_CONFIGURATIONS_EEPROM_EEPROM_CONFIG_H_
#define PRODUCT_WATERHEATER_CONFIGURATIONS_EEPROM_EEPROM_CONFIG_H_

#include "product_main.h"

#define EEPROM_ADDR_CONFIGURATION         (0)
#define EEPROM_SIZE_CONFIGUARTION         (sizeof(S_PRODUCT_CONFIG))
//#define EEPROM_ADDR_AP_SSID               EEPROM_ADDR_CONFIGURATION + EEPROM_SIZE_CONFIGUARTION
//#define EEPROM_SIZE_AP_SSID               sizeof(ap_ssid)
#define EEPROM_ADDR_END                   (EEPROM_ADDR_CONFIGURATION + EEPROM_SIZE_CONFIGUARTION)


#endif /* PRODUCT_WATERHEATER_CONFIGURATIONS_EEPROM_EEPROM_CONFIG_H_ */
