################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src/ESP8266WiFi.cpp \
/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src/ESP8266WiFiAP.cpp \
/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp \
/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src/ESP8266WiFiMulti.cpp \
/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp \
/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src/ESP8266WiFiScan.cpp \
/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src/WiFiClient.cpp \
/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src/WiFiClientSecure.cpp \
/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src/WiFiServer.cpp \
/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src/WiFiUdp.cpp 

LINK_OBJ += \
./libraries/ESP8266WiFi/src/ESP8266WiFi.cpp.o \
./libraries/ESP8266WiFi/src/ESP8266WiFiAP.cpp.o \
./libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp.o \
./libraries/ESP8266WiFi/src/ESP8266WiFiMulti.cpp.o \
./libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp.o \
./libraries/ESP8266WiFi/src/ESP8266WiFiScan.cpp.o \
./libraries/ESP8266WiFi/src/WiFiClient.cpp.o \
./libraries/ESP8266WiFi/src/WiFiClientSecure.cpp.o \
./libraries/ESP8266WiFi/src/WiFiServer.cpp.o \
./libraries/ESP8266WiFi/src/WiFiUdp.cpp.o 

CPP_DEPS += \
./libraries/ESP8266WiFi/src/ESP8266WiFi.cpp.d \
./libraries/ESP8266WiFi/src/ESP8266WiFiAP.cpp.d \
./libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp.d \
./libraries/ESP8266WiFi/src/ESP8266WiFiMulti.cpp.d \
./libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp.d \
./libraries/ESP8266WiFi/src/ESP8266WiFiScan.cpp.d \
./libraries/ESP8266WiFi/src/WiFiClient.cpp.d \
./libraries/ESP8266WiFi/src/WiFiClientSecure.cpp.d \
./libraries/ESP8266WiFi/src/WiFiServer.cpp.d \
./libraries/ESP8266WiFi/src/WiFiUdp.cpp.d 


# Each subdirectory must supply rules for building sources it contributes
libraries/ESP8266WiFi/src/ESP8266WiFi.cpp.o: /home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src/ESP8266WiFi.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/../../../tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/tools/sdk/include" -c -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L  -DARDUINO=10609 -DARDUINO_ESP8266_ESP12 -DARDUINO_ARCH_ESP8266 -DESP8266  -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/cores/esp8266" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/variants/nodemcu" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src" -I"/home/felix/Arduino/libraries/EEPROMAnything" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/EEPROM" -I"/home/felix/Arduino/libraries/DebugUtils" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/Configurations/eeprom" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/MainApp/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/MainApp/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Boot/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Boot/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Data/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Data/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Utils/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Utils/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<" -o "$@"  -Wall
	@echo 'Finished building: $<'
	@echo ' '

libraries/ESP8266WiFi/src/ESP8266WiFiAP.cpp.o: /home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src/ESP8266WiFiAP.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/../../../tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/tools/sdk/include" -c -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L  -DARDUINO=10609 -DARDUINO_ESP8266_ESP12 -DARDUINO_ARCH_ESP8266 -DESP8266  -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/cores/esp8266" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/variants/nodemcu" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src" -I"/home/felix/Arduino/libraries/EEPROMAnything" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/EEPROM" -I"/home/felix/Arduino/libraries/DebugUtils" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/Configurations/eeprom" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/MainApp/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/MainApp/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Boot/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Boot/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Data/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Data/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Utils/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Utils/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<" -o "$@"  -Wall
	@echo 'Finished building: $<'
	@echo ' '

libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp.o: /home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/../../../tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/tools/sdk/include" -c -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L  -DARDUINO=10609 -DARDUINO_ESP8266_ESP12 -DARDUINO_ARCH_ESP8266 -DESP8266  -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/cores/esp8266" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/variants/nodemcu" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src" -I"/home/felix/Arduino/libraries/EEPROMAnything" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/EEPROM" -I"/home/felix/Arduino/libraries/DebugUtils" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/Configurations/eeprom" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/MainApp/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/MainApp/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Boot/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Boot/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Data/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Data/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Utils/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Utils/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<" -o "$@"  -Wall
	@echo 'Finished building: $<'
	@echo ' '

libraries/ESP8266WiFi/src/ESP8266WiFiMulti.cpp.o: /home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src/ESP8266WiFiMulti.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/../../../tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/tools/sdk/include" -c -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L  -DARDUINO=10609 -DARDUINO_ESP8266_ESP12 -DARDUINO_ARCH_ESP8266 -DESP8266  -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/cores/esp8266" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/variants/nodemcu" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src" -I"/home/felix/Arduino/libraries/EEPROMAnything" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/EEPROM" -I"/home/felix/Arduino/libraries/DebugUtils" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/Configurations/eeprom" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/MainApp/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/MainApp/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Boot/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Boot/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Data/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Data/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Utils/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Utils/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<" -o "$@"  -Wall
	@echo 'Finished building: $<'
	@echo ' '

libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp.o: /home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/../../../tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/tools/sdk/include" -c -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L  -DARDUINO=10609 -DARDUINO_ESP8266_ESP12 -DARDUINO_ARCH_ESP8266 -DESP8266  -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/cores/esp8266" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/variants/nodemcu" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src" -I"/home/felix/Arduino/libraries/EEPROMAnything" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/EEPROM" -I"/home/felix/Arduino/libraries/DebugUtils" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/Configurations/eeprom" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/MainApp/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/MainApp/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Boot/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Boot/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Data/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Data/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Utils/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Utils/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<" -o "$@"  -Wall
	@echo 'Finished building: $<'
	@echo ' '

libraries/ESP8266WiFi/src/ESP8266WiFiScan.cpp.o: /home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src/ESP8266WiFiScan.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/../../../tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/tools/sdk/include" -c -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L  -DARDUINO=10609 -DARDUINO_ESP8266_ESP12 -DARDUINO_ARCH_ESP8266 -DESP8266  -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/cores/esp8266" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/variants/nodemcu" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src" -I"/home/felix/Arduino/libraries/EEPROMAnything" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/EEPROM" -I"/home/felix/Arduino/libraries/DebugUtils" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/Configurations/eeprom" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/MainApp/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/MainApp/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Boot/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Boot/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Data/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Data/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Utils/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Utils/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<" -o "$@"  -Wall
	@echo 'Finished building: $<'
	@echo ' '

libraries/ESP8266WiFi/src/WiFiClient.cpp.o: /home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src/WiFiClient.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/../../../tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/tools/sdk/include" -c -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L  -DARDUINO=10609 -DARDUINO_ESP8266_ESP12 -DARDUINO_ARCH_ESP8266 -DESP8266  -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/cores/esp8266" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/variants/nodemcu" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src" -I"/home/felix/Arduino/libraries/EEPROMAnything" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/EEPROM" -I"/home/felix/Arduino/libraries/DebugUtils" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/Configurations/eeprom" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/MainApp/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/MainApp/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Boot/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Boot/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Data/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Data/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Utils/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Utils/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<" -o "$@"  -Wall
	@echo 'Finished building: $<'
	@echo ' '

libraries/ESP8266WiFi/src/WiFiClientSecure.cpp.o: /home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src/WiFiClientSecure.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/../../../tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/tools/sdk/include" -c -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L  -DARDUINO=10609 -DARDUINO_ESP8266_ESP12 -DARDUINO_ARCH_ESP8266 -DESP8266  -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/cores/esp8266" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/variants/nodemcu" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src" -I"/home/felix/Arduino/libraries/EEPROMAnything" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/EEPROM" -I"/home/felix/Arduino/libraries/DebugUtils" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/Configurations/eeprom" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/MainApp/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/MainApp/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Boot/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Boot/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Data/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Data/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Utils/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Utils/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<" -o "$@"  -Wall
	@echo 'Finished building: $<'
	@echo ' '

libraries/ESP8266WiFi/src/WiFiServer.cpp.o: /home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src/WiFiServer.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/../../../tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/tools/sdk/include" -c -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L  -DARDUINO=10609 -DARDUINO_ESP8266_ESP12 -DARDUINO_ARCH_ESP8266 -DESP8266  -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/cores/esp8266" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/variants/nodemcu" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src" -I"/home/felix/Arduino/libraries/EEPROMAnything" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/EEPROM" -I"/home/felix/Arduino/libraries/DebugUtils" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/Configurations/eeprom" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/MainApp/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/MainApp/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Boot/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Boot/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Data/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Data/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Utils/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Utils/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<" -o "$@"  -Wall
	@echo 'Finished building: $<'
	@echo ' '

libraries/ESP8266WiFi/src/WiFiUdp.cpp.o: /home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src/WiFiUdp.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/../../../tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/tools/sdk/include" -c -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L  -DARDUINO=10609 -DARDUINO_ESP8266_ESP12 -DARDUINO_ARCH_ESP8266 -DESP8266  -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/cores/esp8266" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/variants/nodemcu" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/ESP8266WiFi/src" -I"/home/felix/Arduino/libraries/EEPROMAnything" -I"/home/felix/.arduino15/packages/esp8266/hardware/esp8266/2.1.0/libraries/EEPROM" -I"/home/felix/Arduino/libraries/DebugUtils" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/Configurations/eeprom" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/MainApp/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/Product/WaterHeater/MainApp/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Boot/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Boot/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Data/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Data/src" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Utils/inc" -I"/home/felix/Projects/SmartHome/github/SmartHome/SmartHomeWifi/System/Utils/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<" -o "$@"  -Wall
	@echo 'Finished building: $<'
	@echo ' '


